System.config({
  "paths": {
    "*": "*.js",
    "lib/*": "app/lib/*.js",
    "spec/*": "spec/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "~/*": "app/*.js"
  },
  "bundles": {
    "build": [
      "npm:midifile@0.2.0/src/MIDIFileHeader",
      "npm:base64-js@0.0.7/lib/b64",
      "npm:ieee754@1.1.4/index",
      "npm:midievents@0.1.0/src/MIDIEvents",
      "npm:string.fromcodepoint@0.2.1/fromcodepoint",
      "npm:string.prototype.codepointat@0.2.0/codepointat",
      "npm:co@4.0.1/index",
      "~/shims/react",
      "lib/run",
      "npm:js-yaml@3.2.3/lib/js-yaml/common",
      "npm:js-yaml@3.2.3/lib/js-yaml/exception",
      "npm:js-yaml@3.2.3/lib/js-yaml/mark",
      "npm:js-yaml@3.2.3/lib/js-yaml/type",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/str",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/seq",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/map",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/null",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/bool",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/int",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/float",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/timestamp",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/merge",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/binary",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/omap",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/pairs",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/set",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/js/undefined",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/js/regexp",
      "npm:esprima@1.0.4/esprima",
      "npm:js-yaml@3.2.3/lib/js-yaml/dumper",
      "github:components/jquery@2.1.1/jquery",
      "npm:eventemitter3@0.1.6/index",
      "github:jspm/nodelibs@0.0.7/process/index",
      "~/audio",
      "npm:heap@0.2.5/lib/heap",
      "~/midi/note",
      "npm:deep-equal@0.2.1/lib/keys",
      "npm:deep-equal@0.2.1/lib/is_arguments",
      "~/metrics",
      "~/task",
      "~/config",
      "lib/io",
      "~/views/lyrics",
      "lib/evolve",
      "~/views/note",
      "lib/pumper/dom",
      "~/views/options",
      "~/view_models/note",
      "npm:base64-js@0.0.7",
      "npm:ieee754@1.1.4",
      "npm:midievents@0.1.0",
      "npm:string.fromcodepoint@0.2.1",
      "npm:string.prototype.codepointat@0.2.0",
      "npm:co@4.0.1",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema/failsafe",
      "npm:esprima@1.0.4",
      "github:components/jquery@2.1.1",
      "npm:eventemitter3@0.1.6",
      "github:jspm/nodelibs@0.0.7/process",
      "npm:heap@0.2.5/index",
      "npm:deep-equal@0.2.1/index",
      "~/microphone",
      "~/lyrics",
      "app/lib/notes",
      "~/views/notes",
      "~/view_models/notes",
      "github:jspm/nodelibs@0.0.7/buffer/index",
      "npm:utf-8@0.1.2/src/UTF8",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema/json",
      "npm:js-yaml@3.2.3/lib/js-yaml/type/js/function",
      "npm:ramda@0.8.0/ramda",
      "npm:heap@0.2.5",
      "npm:deep-equal@0.2.1",
      "~/models/song",
      "~/renderer",
      "github:jspm/nodelibs@0.0.7/buffer",
      "npm:utf-8@0.1.2",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema/core",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema/default_full",
      "npm:ramda@0.8.0",
      "lib/pumper/pumper",
      "npm:midifile@0.2.0/src/MIDIFileTrack",
      "npm:js-yaml@3.2.3/lib/js-yaml/schema/default_safe",
      "~/player",
      "~/player_volume",
      "npm:midifile@0.2.0/src/MIDIFile",
      "npm:js-yaml@3.2.3/lib/js-yaml/loader",
      "~/application",
      "npm:midifile@0.2.0",
      "npm:js-yaml@3.2.3/lib/js-yaml",
      "npm:js-yaml@3.2.3/index",
      "npm:js-yaml@3.2.3",
      "~/index"
    ]
  }
});

System.config({
  "map": {
    "co": "npm:co@4.0.1",
    "deep-equal": "npm:deep-equal@0.2.1",
    "eventemitter3": "npm:eventemitter3@0.1.6",
    "heap": "npm:heap@0.2.5",
    "jquery": "github:components/jquery@2.1.1",
    "js-yaml": "npm:js-yaml@3.2.3",
    "midievents": "npm:midievents@0.1.0",
    "midifile": "npm:midifile@0.2.0",
    "npm:co": "npm:co@4.0.1",
    "npm:midievents": "npm:midievents@0.1.0",
    "npm:midifile": "npm:midifile@0.2.0",
    "ramda": "npm:ramda@0.8.0",
    "react": "~/shims/react",
    "github:jspm/nodelibs@0.0.7": {
      "Base64": "npm:Base64@0.2.1",
      "base64-js": "npm:base64-js@0.0.7",
      "ieee754": "npm:ieee754@1.1.4",
      "inherits": "npm:inherits@2.0.1",
      "json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:argparse@0.1.16": {
      "underscore": "npm:underscore@1.7.0",
      "underscore.string": "npm:underscore.string@2.4.0"
    },
    "npm:js-yaml@3.2.3": {
      "argparse": "npm:argparse@0.1.16",
      "esprima": "npm:esprima@1.0.4",
      "json": "npm:json@9.0.2"
    },
    "npm:midifile@0.2.0": {
      "midievents": "npm:midievents@0.1.0",
      "utf-8": "npm:utf-8@0.1.2"
    },
    "npm:utf-8@0.1.2": {
      "string.fromcodepoint": "npm:string.fromcodepoint@0.2.1",
      "string.prototype.codepointat": "npm:string.prototype.codepointat@0.2.0"
    }
  }
});

