#!/bin/zsh -e

set -x

BUILD_DIR=/tmp/hymn-build

rm -rf "$BUILD_DIR"
mkdir "$BUILD_DIR"
git archive HEAD | tar x -C "$BUILD_DIR"

(
  cd "$BUILD_DIR"
  harp compile
  mv public source
  mv www public
  jspm install
  jspm bundle '~/index' public/main/app.js --inject
  rm -rf public/jspm_packages
  middleman deploy
)

